ERROR: diagUtilsLib.checkHistoryFiles /glade/collections/cdg/timeseries-cmip6/g.e21.GOMIPECOIAF_JRA.TL319_g17.CMIP6-omip2.001/ice/ice//proc/tseries/month_1 directory is not available.
ERROR: diagUtilsLib.checkHistoryFiles /glade/collections/cdg/timeseries-cmip6/g.e21.GOMIPECOIAF_JRA.TL319_g17.CMIP6-omip2.001/ice/ice//proc/tseries/month_1 directory is not available.
ERROR: diagUtilsLib.checkHistoryFiles /glade/collections/cdg/timeseries-cmip6/g.e21.GOMIPECOIAF_JRA.TL319_g17.CMIP6-omip2.001/ice/ice//proc/tseries/month_1 directory is not available.
ERROR: diagUtilsLib.checkHistoryFiles /glade/collections/cdg/timeseries-cmip6/g.e21.GOMIPECOIAF_JRA.TL319_g17.CMIP6-omip2.001/ice/ice//proc/tseries/month_1 directory is not available.
Traceback (most recent call last):
ERROR: diagUtilsLib.checkHistoryFiles /glade/collections/cdg/timeseries-cmip6/g.e21.GOMIPECOIAF_JRA.TL319_g17.CMIP6-omip2.001/ice/ice//proc/tseries/month_1 directory is not available.
ERROR: diagUtilsLib.checkHistoryFiles /glade/collections/cdg/timeseries-cmip6/g.e21.GOMIPECOIAF_JRA.TL319_g17.CMIP6-omip2.001/ice/ice//proc/tseries/month_1 directory is not available.
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/glade/p/cesm/postprocessing/diagnostics/diagnostics/ice/ice_avg_generator.py", line 412, in main
Traceback (most recent call last):
Traceback (most recent call last):
  File "/glade/p/cesm/postprocessing/diagnostics/diagnostics/ice/ice_avg_generator.py", line 412, in main
  File "/glade/p/cesm/postprocessing/diagnostics/diagnostics/ice/ice_avg_generator.py", line 412, in main
  File "/glade/p/cesm/postprocessing/diagnostics/diagnostics/ice/ice_avg_generator.py", line 412, in main
  File "/glade/p/cesm/postprocessing/diagnostics/diagnostics/ice/ice_avg_generator.py", line 412, in main
  File "/glade/p/cesm/postprocessing/diagnostics/diagnostics/ice/ice_avg_generator.py", line 412, in main
    envDict['PATH_DIFF_SUBDIR'])
    envDict['PATH_DIFF_SUBDIR'])
  File "/glade/p/cesm/postprocessing/diag_utils/diag_utils/diagUtilsLib.py", line 214, in checkHistoryFiles
    envDict['PATH_DIFF_SUBDIR'])
  File "/glade/p/cesm/postprocessing/diag_utils/diag_utils/diagUtilsLib.py", line 214, in checkHistoryFiles
    envDict['PATH_DIFF_SUBDIR'])
  File "/glade/p/cesm/postprocessing/diag_utils/diag_utils/diagUtilsLib.py", line 214, in checkHistoryFiles
  File "/glade/p/cesm/postprocessing/diag_utils/diag_utils/diagUtilsLib.py", line 214, in checkHistoryFiles
    envDict['PATH_DIFF_SUBDIR'])
    envDict['PATH_DIFF_SUBDIR'])
  File "/glade/p/cesm/postprocessing/diag_utils/diag_utils/diagUtilsLib.py", line 214, in checkHistoryFiles
  File "/glade/p/cesm/postprocessing/diag_utils/diag_utils/diagUtilsLib.py", line 214, in checkHistoryFiles
    raise OSError(err_msg)
    raise OSError(err_msg)
    raise OSError(err_msg)
OSError: ERROR: diagUtilsLib.checkHistoryFiles /glade/collections/cdg/timeseries-cmip6/g.e21.GOMIPECOIAF_JRA.TL319_g17.CMIP6-omip2.001/ice/ice//proc/tseries/month_1 directory is not available.
    raise OSError(err_msg)
OSError: ERROR: diagUtilsLib.checkHistoryFiles /glade/collections/cdg/timeseries-cmip6/g.e21.GOMIPECOIAF_JRA.TL319_g17.CMIP6-omip2.001/ice/ice//proc/tseries/month_1 directory is not available.
OSError: ERROR: diagUtilsLib.checkHistoryFiles /glade/collections/cdg/timeseries-cmip6/g.e21.GOMIPECOIAF_JRA.TL319_g17.CMIP6-omip2.001/ice/ice//proc/tseries/month_1 directory is not available.
OSError: ERROR: diagUtilsLib.checkHistoryFiles /glade/collections/cdg/timeseries-cmip6/g.e21.GOMIPECOIAF_JRA.TL319_g17.CMIP6-omip2.001/ice/ice//proc/tseries/month_1 directory is not available.
    raise OSError(err_msg)
ERROR: diagUtilsLib.checkHistoryFiles /glade/collections/cdg/timeseries-cmip6/g.e21.GOMIPECOIAF_JRA.TL319_g17.CMIP6-omip2.001/ice/ice//proc/tseries/month_1 directory is not available.
ERROR: diagUtilsLib.checkHistoryFiles /glade/collections/cdg/timeseries-cmip6/g.e21.GOMIPECOIAF_JRA.TL319_g17.CMIP6-omip2.001/ice/ice//proc/tseries/month_1 directory is not available.
Traceback (most recent call last):
    raise OSError(err_msg)
ERROR: diagUtilsLib.checkHistoryFiles /glade/collections/cdg/timeseries-cmip6/g.e21.GOMIPECOIAF_JRA.TL319_g17.CMIP6-omip2.001/ice/ice//proc/tseries/month_1 directory is not available.
ERROR: diagUtilsLib.checkHistoryFiles /glade/collections/cdg/timeseries-cmip6/g.e21.GOMIPECOIAF_JRA.TL319_g17.CMIP6-omip2.001/ice/ice//proc/tseries/month_1 directory is not available.
Traceback (most recent call last):
OSError: ERROR: diagUtilsLib.checkHistoryFiles /glade/collections/cdg/timeseries-cmip6/g.e21.GOMIPECOIAF_JRA.TL319_g17.CMIP6-omip2.001/ice/ice//proc/tseries/month_1 directory is not available.
Traceback (most recent call last):
Traceback (most recent call last):
  File "/glade/p/cesm/postprocessing/diagnostics/diagnostics/ice/ice_avg_generator.py", line 412, in main
OSError: ERROR: diagUtilsLib.checkHistoryFiles /glade/collections/cdg/timeseries-cmip6/g.e21.GOMIPECOIAF_JRA.TL319_g17.CMIP6-omip2.001/ice/ice//proc/tseries/month_1 directory is not available.
  File "/glade/p/cesm/postprocessing/diagnostics/diagnostics/ice/ice_avg_generator.py", line 412, in main
  File "/glade/p/cesm/postprocessing/diagnostics/diagnostics/ice/ice_avg_generator.py", line 412, in main
  File "/glade/p/cesm/postprocessing/diagnostics/diagnostics/ice/ice_avg_generator.py", line 412, in main
ERROR: diagUtilsLib.checkHistoryFiles /glade/collections/cdg/timeseries-cmip6/g.e21.GOMIPECOIAF_JRA.TL319_g17.CMIP6-omip2.001/ice/ice//proc/tseries/month_1 directory is not available.
ERROR: diagUtilsLib.checkHistoryFiles /glade/collections/cdg/timeseries-cmip6/g.e21.GOMIPECOIAF_JRA.TL319_g17.CMIP6-omip2.001/ice/ice//proc/tseries/month_1 directory is not available.
    envDict['PATH_DIFF_SUBDIR'])
    envDict['PATH_DIFF_SUBDIR'])
Traceback (most recent call last):
    envDict['PATH_DIFF_SUBDIR'])
  File "/glade/p/cesm/postprocessing/diag_utils/diag_utils/diagUtilsLib.py", line 214, in checkHistoryFiles
  File "/glade/p/cesm/postprocessing/diag_utils/diag_utils/diagUtilsLib.py", line 214, in checkHistoryFiles
  File "/glade/p/cesm/postprocessing/diagnostics/diagnostics/ice/ice_avg_generator.py", line 412, in main
  File "/glade/p/cesm/postprocessing/diag_utils/diag_utils/diagUtilsLib.py", line 214, in checkHistoryFiles
ERROR: diagUtilsLib.checkHistoryFiles /glade/collections/cdg/timeseries-cmip6/g.e21.GOMIPECOIAF_JRA.TL319_g17.CMIP6-omip2.001/ice/ice//proc/tseries/month_1 directory is not available.
    envDict['PATH_DIFF_SUBDIR'])
  File "/glade/p/cesm/postprocessing/diag_utils/diag_utils/diagUtilsLib.py", line 214, in checkHistoryFiles
    envDict['PATH_DIFF_SUBDIR'])
Traceback (most recent call last):
Traceback (most recent call last):
    raise OSError(err_msg)
  File "/glade/p/cesm/postprocessing/diag_utils/diag_utils/diagUtilsLib.py", line 214, in checkHistoryFiles
  File "/glade/p/cesm/postprocessing/diagnostics/diagnostics/ice/ice_avg_generator.py", line 412, in main
  File "/glade/p/cesm/postprocessing/diagnostics/diagnostics/ice/ice_avg_generator.py", line 412, in main
    raise OSError(err_msg)
    raise OSError(err_msg)
    raise OSError(err_msg)
    raise OSError(err_msg)
OSError: ERROR: diagUtilsLib.checkHistoryFiles /glade/collections/cdg/timeseries-cmip6/g.e21.GOMIPECOIAF_JRA.TL319_g17.CMIP6-omip2.001/ice/ice//proc/tseries/month_1 directory is not available.
OSError: ERROR: diagUtilsLib.checkHistoryFiles /glade/collections/cdg/timeseries-cmip6/g.e21.GOMIPECOIAF_JRA.TL319_g17.CMIP6-omip2.001/ice/ice//proc/tseries/month_1 directory is not available.
OSError: ERROR: diagUtilsLib.checkHistoryFiles /glade/collections/cdg/timeseries-cmip6/g.e21.GOMIPECOIAF_JRA.TL319_g17.CMIP6-omip2.001/ice/ice//proc/tseries/month_1 directory is not available.
OSError: ERROR: diagUtilsLib.checkHistoryFiles /glade/collections/cdg/timeseries-cmip6/g.e21.GOMIPECOIAF_JRA.TL319_g17.CMIP6-omip2.001/ice/ice//proc/tseries/month_1 directory is not available.
OSError: ERROR: diagUtilsLib.checkHistoryFiles /glade/collections/cdg/timeseries-cmip6/g.e21.GOMIPECOIAF_JRA.TL319_g17.CMIP6-omip2.001/ice/ice//proc/tseries/month_1 directory is not available.
ERROR: diagUtilsLib.checkHistoryFiles /glade/collections/cdg/timeseries-cmip6/g.e21.GOMIPECOIAF_JRA.TL319_g17.CMIP6-omip2.001/ice/ice//proc/tseries/month_1 directory is not available.
    envDict['PATH_DIFF_SUBDIR'])
    envDict['PATH_DIFF_SUBDIR'])
ERROR: diagUtilsLib.checkHistoryFiles /glade/collections/cdg/timeseries-cmip6/g.e21.GOMIPECOIAF_JRA.TL319_g17.CMIP6-omip2.001/ice/ice//proc/tseries/month_1 directory is not available.
Traceback (most recent call last):
  File "/glade/p/cesm/postprocessing/diag_utils/diag_utils/diagUtilsLib.py", line 214, in checkHistoryFiles
  File "/glade/p/cesm/postprocessing/diag_utils/diag_utils/diagUtilsLib.py", line 214, in checkHistoryFiles
Traceback (most recent call last):
  File "/glade/p/cesm/postprocessing/diagnostics/diagnostics/ice/ice_avg_generator.py", line 412, in main
    raise OSError(err_msg)
    raise OSError(err_msg)
  File "/glade/p/cesm/postprocessing/diagnostics/diagnostics/ice/ice_avg_generator.py", line 412, in main
    envDict['PATH_DIFF_SUBDIR'])
OSError: ERROR: diagUtilsLib.checkHistoryFiles /glade/collections/cdg/timeseries-cmip6/g.e21.GOMIPECOIAF_JRA.TL319_g17.CMIP6-omip2.001/ice/ice//proc/tseries/month_1 directory is not available.
OSError: ERROR: diagUtilsLib.checkHistoryFiles /glade/collections/cdg/timeseries-cmip6/g.e21.GOMIPECOIAF_JRA.TL319_g17.CMIP6-omip2.001/ice/ice//proc/tseries/month_1 directory is not available.
    envDict['PATH_DIFF_SUBDIR'])
  File "/glade/p/cesm/postprocessing/diag_utils/diag_utils/diagUtilsLib.py", line 214, in checkHistoryFiles
  File "/glade/p/cesm/postprocessing/diag_utils/diag_utils/diagUtilsLib.py", line 214, in checkHistoryFiles
    raise OSError(err_msg)
ERROR: diagUtilsLib.checkHistoryFiles /glade/collections/cdg/timeseries-cmip6/g.e21.GOMIPECOIAF_JRA.TL319_g17.CMIP6-omip2.001/ice/ice//proc/tseries/month_1 directory is not available.
OSError: ERROR: diagUtilsLib.checkHistoryFiles /glade/collections/cdg/timeseries-cmip6/g.e21.GOMIPECOIAF_JRA.TL319_g17.CMIP6-omip2.001/ice/ice//proc/tseries/month_1 directory is not available.
Traceback (most recent call last):
  File "/glade/p/cesm/postprocessing/diagnostics/diagnostics/ice/ice_avg_generator.py", line 412, in main
    raise OSError(err_msg)
OSError: ERROR: diagUtilsLib.checkHistoryFiles /glade/collections/cdg/timeseries-cmip6/g.e21.GOMIPECOIAF_JRA.TL319_g17.CMIP6-omip2.001/ice/ice//proc/tseries/month_1 directory is not available.
    envDict['PATH_DIFF_SUBDIR'])
  File "/glade/p/cesm/postprocessing/diag_utils/diag_utils/diagUtilsLib.py", line 214, in checkHistoryFiles
    raise OSError(err_msg)
OSError: ERROR: diagUtilsLib.checkHistoryFiles /glade/collections/cdg/timeseries-cmip6/g.e21.GOMIPECOIAF_JRA.TL319_g17.CMIP6-omip2.001/ice/ice//proc/tseries/month_1 directory is not available.
